//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class department_user_master
    {
        public decimal dept_user_id { get; set; }
        public decimal organization_id { get; set; }
        public decimal office_id { get; set; }
        public decimal role_id { get; set; }
        public string username { get; set; }
        public decimal designation_id { get; set; }
        public decimal reporting_office_id { get; set; }
        public decimal reporting_role_id { get; set; }
        public decimal mobile_no { get; set; }
        public string email_id { get; set; }
        public string password { get; set; }
        public decimal status_id { get; set; }
        public string TRIAL009 { get; set; }
    
        public virtual designation_master designation_master { get; set; }
        public virtual role_master role_master { get; set; }
        public virtual role_master role_master1 { get; set; }
        public virtual status_master status_master { get; set; }
    }
}
