//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class final_recommendation
    {
        public decimal fr_id { get; set; }
        public Nullable<decimal> application_number { get; set; }
        public Nullable<decimal> rs_id { get; set; }
        public string remarks { get; set; }
        public string recommendation_note { get; set; }
        public Nullable<System.DateTime> recommendation_date { get; set; }
        public Nullable<decimal> recommended_by { get; set; }
        public Nullable<System.DateTime> go_date { get; set; }
        public string original_filename { get; set; }
        public string revised_filename { get; set; }
        public string go_number { get; set; }
        public string TRIAL012 { get; set; }
    
        public virtual project_details project_details { get; set; }
        public virtual recommendation_status_master recommendation_status_master { get; set; }
    }
}
