//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday_master
    {
        public int hm_id { get; set; }
        public string date { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date12 { get; set; }
        public string TRIAL012 { get; set; }
    }
}
