//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class kum_storage_details
    {
        public decimal sd_id { get; set; }
        public Nullable<decimal> kum_id { get; set; }
        public Nullable<int> stm_id { get; set; }
        public Nullable<int> shape_id { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> breadth { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> radius { get; set; }
        public Nullable<decimal> capacity { get; set; }
        public string TRIAL015 { get; set; }
    
        public virtual kum_project_details kum_project_details { get; set; }
        public virtual shape_master shape_master { get; set; }
        public virtual structure_type_master structure_type_master { get; set; }
    }
}
