//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class kum_document_details
    {
        public decimal dd_id { get; set; }
        public Nullable<decimal> kum_id { get; set; }
        public Nullable<decimal> doc_type_id { get; set; }
        public string original_filename { get; set; }
        public string revised_filename { get; set; }
        public Nullable<System.DateTime> updaated_date { get; set; }
        public Nullable<decimal> updated_by { get; set; }
        public string TRIAL012 { get; set; }
    
        public virtual user_details user_details { get; set; }
        public virtual kum_document_type_master kum_document_type_master { get; set; }
        public virtual kum_project_details kum_project_details { get; set; }
    }
}
