//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_statistics
    {
        public decimal loginid { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public Nullable<System.DateTime> login { get; set; }
        public Nullable<System.DateTime> logout { get; set; }
        public string ip { get; set; }
        public string status { get; set; }
        public string duration { get; set; }
        public string TRIAL019 { get; set; }
    
        public virtual user_details user_details { get; set; }
    }
}
