//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class measures_details
    {
        public decimal md_id { get; set; }
        public Nullable<decimal> application_number { get; set; }
        public string technology_adapted { get; set; }
        public Nullable<decimal> demand { get; set; }
        public Nullable<decimal> savings { get; set; }
        public Nullable<decimal> unit_id { get; set; }
        public Nullable<int> measure_id { get; set; }
        public string TRIAL019 { get; set; }
    
        public virtual measure_master measure_master { get; set; }
        public virtual project_details project_details { get; set; }
        public virtual unit_master unit_master { get; set; }
    }
}
