//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menu_details()
        {
            this.menu_role_assoc = new HashSet<menu_role_assoc>();
            this.menu_submenu_assoc = new HashSet<menu_submenu_assoc>();
            this.menu_submenu_assoc1 = new HashSet<menu_submenu_assoc>();
        }
    
        public decimal menu_id { get; set; }
        public string menu_item_id { get; set; }
        public string menu_desc { get; set; }
        public string menu_url { get; set; }
        public Nullable<decimal> is_direct_menu_link { get; set; }
        public Nullable<decimal> is_menu_header { get; set; }
        public Nullable<decimal> menu_order { get; set; }
        public string menu_style_class_name { get; set; }
        public string comma_sep_child_urls { get; set; }
        public string TRIAL019 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu_role_assoc> menu_role_assoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu_submenu_assoc> menu_submenu_assoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu_submenu_assoc> menu_submenu_assoc1 { get; set; }
    }
}
