//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_role_assoc
    {
        public decimal menu_id { get; set; }
        public decimal role_id { get; set; }
        public string TRIAL019 { get; set; }
    
        public virtual menu_details menu_details { get; set; }
        public virtual role_master role_master { get; set; }
    }
}
