//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class office_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public office_master()
        {
            this.project_status = new HashSet<project_status>();
            this.project_status1 = new HashSet<project_status>();
            this.user_details = new HashSet<user_details>();
            this.user_details1 = new HashSet<user_details>();
        }
    
        public decimal office_master_id { get; set; }
        public decimal organization_id { get; set; }
        public decimal office_type_id { get; set; }
        public string office_name { get; set; }
        public string address { get; set; }
        public string landline_no { get; set; }
        public Nullable<decimal> mobile_no { get; set; }
        public string fax_no { get; set; }
        public string email_id { get; set; }
        public Nullable<decimal> branch { get; set; }
        public Nullable<decimal> multiple { get; set; }
        public string TRIAL022 { get; set; }
    
        public virtual office_type_master office_type_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_status> project_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_status> project_status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_details> user_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_details> user_details1 { get; set; }
    }
}
