//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class office_recommendation_upload
    {
        public int oru_id { get; set; }
        public Nullable<int> office_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string recommendation { get; set; }
        public string original_filename { get; set; }
        public string revised_filename { get; set; }
        public Nullable<int> application_number { get; set; }
        public Nullable<decimal> branch { get; set; }
        public Nullable<decimal> project_status_id { get; set; }
        public string TRIAL022 { get; set; }
    }
}
