//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_status
    {
        public double payment_id { get; set; }
        public string dept_ref_num { get; set; }
        public string bank_ref_num { get; set; }
        public string pymnt_status { get; set; }
        public string pymnt_mode { get; set; }
        public string bank_name { get; set; }
        public Nullable<double> paid_amount { get; set; }
        public string current_time_stamp { get; set; }
        public string status_code { get; set; }
        public string status_desc { get; set; }
        public string TRIAL025 { get; set; }
    }
}
