//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_details
    {
        public string dept_ref_no { get; set; }
        public Nullable<double> application_number { get; set; }
        public string agency_code { get; set; }
        public string integration_code { get; set; }
        public string uri_no { get; set; }
        public string chln_date { get; set; }
        public string dept_code { get; set; }
        public string ddo_code { get; set; }
        public Nullable<double> amount { get; set; }
        public string prpsname { get; set; }
        public string rmtrname { get; set; }
        public string trsrycode { get; set; }
        public string TRIAL025 { get; set; }
    }
}
