//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_status
    {
        public Nullable<decimal> application_number { get; set; }
        public decimal project_status_id { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> office_master_id { get; set; }
        public Nullable<decimal> role_id { get; set; }
        public Nullable<decimal> assigned_to_office_id { get; set; }
        public Nullable<decimal> assigned_to_role_id { get; set; }
        public Nullable<decimal> assigned_from_role_id { get; set; }
        public string assigned_from_office_id { get; set; }
        public Nullable<decimal> branch { get; set; }
        public Nullable<decimal> flag { get; set; }
        public Nullable<double> day_limit { get; set; }
        public string payment_ref_num { get; set; }
        public string payment_status { get; set; }
        public Nullable<double> payment_id { get; set; }
        public string TRIAL028 { get; set; }
    
        public virtual office_master office_master { get; set; }
        public virtual office_master office_master1 { get; set; }
        public virtual project_details project_details { get; set; }
        public virtual project_status_master project_status_master { get; set; }
        public virtual role_master role_master { get; set; }
        public virtual role_master role_master1 { get; set; }
        public virtual user_details user_details { get; set; }
    }
}
