//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_status_master
    {
        public decimal proj_status_id { get; set; }
        public string description { get; set; }
        public string display_status { get; set; }
        public string remarks { get; set; }
        public string owner_role_id { get; set; }
        public Nullable<decimal> order_by { get; set; }
        public string description_next_status { get; set; }
        public string TRIAL028 { get; set; }
    
        public virtual project_status project_status { get; set; }
    }
}
