//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_next_status
    {
        public Nullable<decimal> app_current_status_id { get; set; }
        public Nullable<decimal> app_next_status_id { get; set; }
        public Nullable<decimal> office_master_id { get; set; }
        public Nullable<decimal> role_id { get; set; }
        public Nullable<decimal> prev_role_id { get; set; }
        public Nullable<decimal> to_office_master_id { get; set; }
        public Nullable<decimal> to_role_id { get; set; }
        public string prev_office_master_id { get; set; }
        public Nullable<decimal> days_limit { get; set; }
        public decimal pns_id { get; set; }
        public Nullable<decimal> branch { get; set; }
        public string TRIAL025 { get; set; }
    }
}
