//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_details()
        {
            this.document_details = new HashSet<document_details>();
            this.final_recommendation = new HashSet<final_recommendation>();
            this.land_ownership_details = new HashSet<land_ownership_details>();
            this.measures_details = new HashSet<measures_details>();
            this.project_status = new HashSet<project_status>();
            this.storage_details = new HashSet<storage_details>();
        }
    
        public decimal application_number { get; set; }
        public Nullable<int> icm_id { get; set; }
        public Nullable<int> ism_id { get; set; }
        public Nullable<decimal> dw_lat_d { get; set; }
        public Nullable<decimal> dw_lat_m { get; set; }
        public Nullable<decimal> dw_lat_s { get; set; }
        public Nullable<decimal> dw_long_d { get; set; }
        public Nullable<decimal> dw_long_m { get; set; }
        public Nullable<decimal> dw_long_s { get; set; }
        public Nullable<decimal> dw_frl { get; set; }
        public Nullable<decimal> dw_rbl { get; set; }
        public Nullable<decimal> basin_type_id { get; set; }
        public Nullable<decimal> water_source_id { get; set; }
        public Nullable<int> wsa_id { get; set; }
        public Nullable<decimal> catchment_area { get; set; }
        public Nullable<decimal> req_per_day { get; set; }
        public Nullable<decimal> req_pd_unit_id { get; set; }
        public Nullable<decimal> no_months { get; set; }
        public Nullable<int> from_month_id { get; set; }
        public Nullable<int> to_month_id { get; set; }
        public Nullable<decimal> no_days { get; set; }
        public Nullable<int> from_day_month_id { get; set; }
        public Nullable<int> from_day_id { get; set; }
        public Nullable<int> to_day_month_id { get; set; }
        public Nullable<int> to_day_id { get; set; }
        public Nullable<decimal> req_yearly { get; set; }
        public Nullable<decimal> req_yearly_unit_id { get; set; }
        public Nullable<decimal> no_days_power_generated { get; set; }
        public Nullable<decimal> location_village_id { get; set; }
        public Nullable<decimal> lp_village_id { get; set; }
        public Nullable<decimal> lp_lat_d { get; set; }
        public Nullable<decimal> lp_lat_m { get; set; }
        public Nullable<decimal> lp_lat_s { get; set; }
        public Nullable<decimal> lp_long_d { get; set; }
        public Nullable<decimal> lp_long_m { get; set; }
        public Nullable<decimal> lp_long_s { get; set; }
        public string pipeline_proposed { get; set; }
        public Nullable<decimal> head_available { get; set; }
        public Nullable<decimal> water_avail_dpr { get; set; }
        public Nullable<decimal> water_avail_unit_id { get; set; }
        public string water_avail_method_dpr { get; set; }
        public string irrigation_effect { get; set; }
        public string private_public_effect { get; set; }
        public string remedial_measures { get; set; }
        public Nullable<decimal> created_by { get; set; }
        public Nullable<decimal> modified_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public string river_name { get; set; }
        public Nullable<int> dmm_id { get; set; }
        public Nullable<decimal> river_basin_id { get; set; }
        public Nullable<decimal> rsm_id { get; set; }
        public Nullable<decimal> req_period_id { get; set; }
        public Nullable<decimal> minihydro_capacity { get; set; }
        public Nullable<decimal> minihydro_capacity_unit { get; set; }
        public Nullable<int> total_turbines { get; set; }
        public Nullable<decimal> per_turbine_min_unit { get; set; }
        public Nullable<decimal> per_turbine_max_unit { get; set; }
        public string per_turbine_min { get; set; }
        public string per_turbine_max { get; set; }
        public string allocation_already_made { get; set; }
        public string processing_fee { get; set; }
        public string water_use_charges { get; set; }
        public Nullable<System.DateTime> challen_date { get; set; }
        public string challen_number { get; set; }
        public string TRIAL025 { get; set; }
    
        public virtual basin_type_master basin_type_master { get; set; }
        public virtual day_master day_master { get; set; }
        public virtual day_master day_master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document_details> document_details { get; set; }
        public virtual drawal_mode_master drawal_mode_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<final_recommendation> final_recommendation { get; set; }
        public virtual industry_category_master industry_category_master { get; set; }
        public virtual industry_status_master industry_status_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<land_ownership_details> land_ownership_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<measures_details> measures_details { get; set; }
        public virtual month_master month_master { get; set; }
        public virtual month_master month_master1 { get; set; }
        public virtual month_master month_master2 { get; set; }
        public virtual month_master month_master3 { get; set; }
        public virtual user_details user_details { get; set; }
        public virtual village_master village_master { get; set; }
        public virtual village_master village_master1 { get; set; }
        public virtual user_details user_details1 { get; set; }
        public virtual unit_master unit_master { get; set; }
        public virtual unit_master unit_master1 { get; set; }
        public virtual unit_master unit_master2 { get; set; }
        public virtual water_source_master water_source_master { get; set; }
        public virtual water_source_availability_master water_source_availability_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_status> project_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storage_details> storage_details { get; set; }
        public virtual unit_master unit_master3 { get; set; }
    }
}
