//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_inspection_allocation
    {
        public int sia_id { get; set; }
        public Nullable<decimal> si_id { get; set; }
        public Nullable<decimal> overall_allocation { get; set; }
        public Nullable<decimal> allocation_available { get; set; }
        public Nullable<decimal> permission_given { get; set; }
        public Nullable<decimal> balance_available { get; set; }
        public Nullable<decimal> industry_requirement { get; set; }
        public Nullable<decimal> branch { get; set; }
        public Nullable<decimal> application_number { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public Nullable<decimal> allocation_avail_unit_id { get; set; }
        public Nullable<decimal> permission_given_unit_id { get; set; }
        public Nullable<decimal> balance_available_unit_id { get; set; }
        public Nullable<decimal> industry_req_unit_id { get; set; }
        public Nullable<decimal> overall_alloc_unit_id { get; set; }
        public string TRIAL032 { get; set; }
    
        public virtual site_inspection_report site_inspection_report { get; set; }
    }
}
