//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_inspection_details
    {
        public decimal si_id { get; set; }
        public Nullable<decimal> application_number { get; set; }
        public Nullable<decimal> overall_allocation { get; set; }
        public Nullable<decimal> al_overall_allocation_unit { get; set; }
        public Nullable<decimal> al_allocation_available { get; set; }
        public Nullable<decimal> al_allocation_available_unit { get; set; }
        public Nullable<decimal> al_permission_given { get; set; }
        public Nullable<decimal> al_permission_given_unit { get; set; }
        public Nullable<decimal> al_balance_available { get; set; }
        public Nullable<decimal> al_balance_available_unit { get; set; }
        public Nullable<decimal> al_requirement { get; set; }
        public Nullable<decimal> al_requirement_unit { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> aow_entrypoint { get; set; }
        public Nullable<decimal> aow_entrypoint_unit { get; set; }
        public Nullable<decimal> aoq_quantum_utilized { get; set; }
        public Nullable<decimal> aow_quantum_utilized_unit { get; set; }
        public Nullable<decimal> aow_quantum_utilized_at_exit { get; set; }
        public Nullable<decimal> aow_quantum_utilized_exit_unit { get; set; }
        public string methodology { get; set; }
        public Nullable<decimal> man_actual_requirement { get; set; }
        public Nullable<decimal> man_actual_requirement_unit { get; set; }
        public Nullable<decimal> man_savings { get; set; }
        public Nullable<decimal> man_savings_unit { get; set; }
        public Nullable<decimal> man_revised_requirement { get; set; }
        public Nullable<decimal> man_revised_requirement_unit { get; set; }
        public Nullable<decimal> clean_actual_requirement { get; set; }
        public Nullable<decimal> clean_actual_req_unit { get; set; }
        public Nullable<decimal> clean_savings { get; set; }
        public Nullable<decimal> clean_savings_unit { get; set; }
        public Nullable<decimal> clean_revised_requirement { get; set; }
        public Nullable<decimal> clean_revised_req_unit { get; set; }
        public Nullable<decimal> cool_actual_requirement { get; set; }
        public Nullable<decimal> cool_actual_req_unit { get; set; }
        public Nullable<decimal> cool_savings { get; set; }
        public Nullable<decimal> cool_savings_unit { get; set; }
        public Nullable<decimal> cool_revised_requirement { get; set; }
        public Nullable<decimal> cool_revised_req_unit { get; set; }
        public Nullable<decimal> dom_purp_actual_requirement { get; set; }
        public Nullable<decimal> dom_purp_actual_req_unit { get; set; }
        public Nullable<decimal> dom_purp_savings { get; set; }
        public Nullable<decimal> dom_purp_savings_unit { get; set; }
        public Nullable<decimal> dom_purp_revised_requirement { get; set; }
        public Nullable<decimal> dom_purp_revised_req_unit { get; set; }
        public Nullable<decimal> util_sep_actual_requirement { get; set; }
        public Nullable<decimal> util_sep_actual_req_unit { get; set; }
        public Nullable<decimal> util_sep_savings { get; set; }
        public Nullable<decimal> util_sep_savings_unit { get; set; }
        public Nullable<decimal> util_sep_revised_requirement { get; set; }
        public Nullable<decimal> util_sep_revised_req_unit { get; set; }
        public Nullable<decimal> util_int_actual_requirement { get; set; }
        public Nullable<decimal> util_int_actual_req_unit { get; set; }
        public Nullable<decimal> util_int_savings { get; set; }
        public Nullable<decimal> util_int_savings_unit { get; set; }
        public Nullable<decimal> util_int_revised_requirement { get; set; }
        public Nullable<decimal> util_int_revised_req_unit { get; set; }
        public Nullable<decimal> conjunctive_actual_requirement { get; set; }
        public Nullable<decimal> conjunctive_actual_req_unit { get; set; }
        public Nullable<decimal> conjunctive_savings { get; set; }
        public Nullable<decimal> conjunctive_savings_unit { get; set; }
        public Nullable<decimal> conjunctive_revised_requirement { get; set; }
        public Nullable<decimal> conjunctive_revised_req_unit { get; set; }
        public Nullable<decimal> recycle_actual_requirement { get; set; }
        public Nullable<decimal> recycle_actual_req_unit { get; set; }
        public Nullable<decimal> recycle_savings { get; set; }
        public Nullable<decimal> recycle_savings_unit { get; set; }
        public Nullable<decimal> recycle_revised_requirement { get; set; }
        public Nullable<decimal> recycle_revised_req_unit { get; set; }
        public Nullable<decimal> treated_actual_requirement { get; set; }
        public Nullable<decimal> treated_actual_req_unit { get; set; }
        public Nullable<decimal> treated_savings { get; set; }
        public Nullable<decimal> treated_savings_unit { get; set; }
        public Nullable<decimal> treated_revised_requirement { get; set; }
        public Nullable<decimal> treated_revised_req_unit { get; set; }
        public Nullable<decimal> rwh_actual_requirement { get; set; }
        public Nullable<decimal> rwh_actual_req_unit { get; set; }
        public Nullable<decimal> rwh_savings { get; set; }
        public Nullable<decimal> rwh_savings_unit { get; set; }
        public Nullable<decimal> rwh_revised_requirement { get; set; }
        public Nullable<decimal> rwh_revised_req_unit { get; set; }
        public string op_irrigation_way { get; set; }
        public Nullable<decimal> op_effect { get; set; }
        public string op_effect_note { get; set; }
        public Nullable<decimal> op_pollution { get; set; }
        public string op_pollution_note { get; set; }
        public string op_avoid_provision { get; set; }
        public Nullable<decimal> op_provosion_acceptable { get; set; }
        public string op_provosion_acceptable_note { get; set; }
        public Nullable<decimal> op_whether_accepted { get; set; }
        public string op_whether_accepted_note { get; set; }
        public Nullable<decimal> pis_id { get; set; }
        public Nullable<decimal> svg_by_seepage { get; set; }
        public Nullable<decimal> svg_by_seepage_unit { get; set; }
        public Nullable<decimal> svg_by_savings { get; set; }
        public Nullable<decimal> svg_by_savings_unit { get; set; }
        public string appraisal_location { get; set; }
        public Nullable<decimal> appr_water_availability { get; set; }
        public Nullable<decimal> appr_water_availability_unit { get; set; }
        public Nullable<decimal> appr_ar_id { get; set; }
        public string wrdo_scrutiny { get; set; }
        public string wrdo_interstate_clearance { get; set; }
        public string wrdo_committee_clearance { get; set; }
        public string wrdo_final_recommendation { get; set; }
        public string original_filename { get; set; }
        public string revised_filename { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<decimal> created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<decimal> modified_by { get; set; }
        public Nullable<System.DateTime> inspection_from_date { get; set; }
        public Nullable<System.DateTime> inspection_to_date { get; set; }
        public Nullable<int> status_id { get; set; }
        public string TRIAL032 { get; set; }
    
        public virtual appraisal_recommendation_master appraisal_recommendation_master { get; set; }
        public virtual proposed_industry_status proposed_industry_status { get; set; }
        public virtual unit_master unit_master { get; set; }
        public virtual unit_master unit_master1 { get; set; }
        public virtual unit_master unit_master2 { get; set; }
        public virtual unit_master unit_master3 { get; set; }
        public virtual unit_master unit_master4 { get; set; }
        public virtual unit_master unit_master5 { get; set; }
        public virtual unit_master unit_master6 { get; set; }
        public virtual unit_master unit_master7 { get; set; }
        public virtual unit_master unit_master8 { get; set; }
        public virtual unit_master unit_master9 { get; set; }
        public virtual unit_master unit_master10 { get; set; }
        public virtual unit_master unit_master11 { get; set; }
        public virtual unit_master unit_master12 { get; set; }
        public virtual unit_master unit_master13 { get; set; }
        public virtual unit_master unit_master14 { get; set; }
        public virtual unit_master unit_master15 { get; set; }
        public virtual unit_master unit_master16 { get; set; }
        public virtual user_details user_details { get; set; }
        public virtual unit_master unit_master17 { get; set; }
        public virtual unit_master unit_master18 { get; set; }
        public virtual unit_master unit_master19 { get; set; }
        public virtual unit_master unit_master20 { get; set; }
        public virtual unit_master unit_master21 { get; set; }
        public virtual unit_master unit_master22 { get; set; }
        public virtual user_details user_details1 { get; set; }
        public virtual unit_master unit_master23 { get; set; }
        public virtual yes_no_master yes_no_master { get; set; }
        public virtual yes_no_master yes_no_master1 { get; set; }
        public virtual yes_no_master yes_no_master2 { get; set; }
        public virtual yes_no_master yes_no_master3 { get; set; }
        public virtual unit_master unit_master24 { get; set; }
        public virtual unit_master unit_master25 { get; set; }
        public virtual unit_master unit_master26 { get; set; }
        public virtual unit_master unit_master27 { get; set; }
        public virtual unit_master unit_master28 { get; set; }
        public virtual unit_master unit_master29 { get; set; }
        public virtual unit_master unit_master30 { get; set; }
        public virtual unit_master unit_master31 { get; set; }
        public virtual unit_master unit_master32 { get; set; }
        public virtual unit_master unit_master33 { get; set; }
        public virtual unit_master unit_master34 { get; set; }
        public virtual unit_master unit_master35 { get; set; }
        public virtual unit_master unit_master36 { get; set; }
        public virtual unit_master unit_master37 { get; set; }
        public virtual unit_master unit_master38 { get; set; }
        public virtual unit_master unit_master39 { get; set; }
        public virtual unit_master unit_master40 { get; set; }
    }
}
