//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_inspection_report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public site_inspection_report()
        {
            this.site_inspection_allocation = new HashSet<site_inspection_allocation>();
            this.site_inspection_conditions = new HashSet<site_inspection_conditions>();
        }
    
        public Nullable<decimal> industry_type_id { get; set; }
        public Nullable<decimal> village_id { get; set; }
        public Nullable<decimal> hyd_lat_d { get; set; }
        public Nullable<decimal> hyd_lat_m { get; set; }
        public Nullable<decimal> hyd_lat_s { get; set; }
        public Nullable<decimal> hyd_long_d { get; set; }
        public Nullable<decimal> hyd_long_m { get; set; }
        public Nullable<decimal> hyd_long_s { get; set; }
        public Nullable<int> ism_id { get; set; }
        public Nullable<decimal> basin_type_id { get; set; }
        public Nullable<decimal> river_basin_id { get; set; }
        public Nullable<decimal> rsm_id { get; set; }
        public Nullable<decimal> water_source_id { get; set; }
        public Nullable<int> wsa_id { get; set; }
        public Nullable<int> status_proposed_id { get; set; }
        public string place_loc_hydroproject { get; set; }
        public Nullable<decimal> hyd_dw_lat_d { get; set; }
        public Nullable<decimal> hyd_dw_lat_m { get; set; }
        public Nullable<decimal> hyd_dw_lat_s { get; set; }
        public Nullable<decimal> hyd_dw_long_d { get; set; }
        public Nullable<decimal> hyd_dw_long_m { get; set; }
        public Nullable<decimal> hyd_dw_long_s { get; set; }
        public string hyd_minihydro_capacity { get; set; }
        public string hyd_frl { get; set; }
        public string hyd_mwl { get; set; }
        public string hyd_hfl { get; set; }
        public string hyd_rbl { get; set; }
        public string hyd_requirement { get; set; }
        public string hyd_no_days_power_generated { get; set; }
        public string hyd_head_available { get; set; }
        public string hyd_catchment_area { get; set; }
        public string hyd_water_avail_dpr { get; set; }
        public string hyd_access_spot_nhsh { get; set; }
        public string hyd_effect_water_supply { get; set; }
        public string hyd_effect_on_irrigation { get; set; }
        public string hyd_effect_public_structure { get; set; }
        public string hyd_rr_involvement { get; set; }
        public string hyd_submergence_area_details { get; set; }
        public string hyd_relevant_info { get; set; }
        public decimal si_id { get; set; }
        public Nullable<decimal> ind_req_per_day { get; set; }
        public Nullable<decimal> ind_req_pd_unit { get; set; }
        public Nullable<decimal> ind_req_period_id { get; set; }
        public Nullable<decimal> ind_no_months { get; set; }
        public Nullable<int> ind_from_month_id { get; set; }
        public Nullable<int> ind_to_month_id { get; set; }
        public Nullable<decimal> ind_no_days { get; set; }
        public Nullable<int> ind_from_day_month_id { get; set; }
        public Nullable<int> ind_from_day_id { get; set; }
        public Nullable<int> ind_to_day_month_id { get; set; }
        public Nullable<int> ind_to_day_id { get; set; }
        public string ind_req_yearly { get; set; }
        public Nullable<int> dmm_id { get; set; }
        public string ind_storage_pipeline_proposed { get; set; }
        public string ind_water_avail_mdce_wrdo { get; set; }
        public string ind_water_avail_method_cewrdo { get; set; }
        public Nullable<int> ind_for_manufacture { get; set; }
        public Nullable<int> ind_for_cleaning { get; set; }
        public Nullable<int> ind_for_cooling { get; set; }
        public Nullable<int> ind_for_domestic { get; set; }
        public Nullable<int> ind_utilise_seperate { get; set; }
        public Nullable<int> ind_utilise_series { get; set; }
        public Nullable<int> ind_conjuctive_use { get; set; }
        public Nullable<int> ind_recycle_water { get; set; }
        public Nullable<int> ind_waste_water { get; set; }
        public Nullable<int> ind_rain_harvest { get; set; }
        public Nullable<decimal> ind_irrigation_way { get; set; }
        public Nullable<decimal> ind_affect_drinking_water { get; set; }
        public Nullable<int> ind_pollute_sorrounding { get; set; }
        public Nullable<int> ind_provision_effect_irrigation { get; set; }
        public Nullable<int> ind_remedial_measures { get; set; }
        public Nullable<int> ind_whether_acceptable { get; set; }
        public Nullable<decimal> ind_by_seepage { get; set; }
        public Nullable<decimal> ind_savings_atchkat { get; set; }
        public string ind_location_required { get; set; }
        public Nullable<decimal> ind_moef { get; set; }
        public Nullable<decimal> ind_kspcb { get; set; }
        public Nullable<decimal> ind_kptcl_escom { get; set; }
        public Nullable<decimal> ind_land_acquisition_details { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<decimal> created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<decimal> modified_by { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<decimal> lp_village_id { get; set; }
        public Nullable<decimal> application_number { get; set; }
        public Nullable<int> ind_whether_accepted { get; set; }
        public Nullable<decimal> ind_lp_lat_d { get; set; }
        public Nullable<decimal> ind_lp_lat_m { get; set; }
        public Nullable<decimal> ind_lp_lat_s { get; set; }
        public Nullable<decimal> ind_lp_long_d { get; set; }
        public Nullable<decimal> ind_lp_long_m { get; set; }
        public Nullable<decimal> ind_lp_long_s { get; set; }
        public Nullable<decimal> branch { get; set; }
        public string industry_capacity { get; set; }
        public Nullable<decimal> hyd_water_avail_dpr_unit { get; set; }
        public Nullable<decimal> hyd_requirement_unit { get; set; }
        public Nullable<decimal> industry_capacity_unit_id { get; set; }
        public Nullable<decimal> ind_req_yearly_unit_id { get; set; }
        public string TRIAL035 { get; set; }
    
        public virtual basin_type_master basin_type_master { get; set; }
        public virtual industry_status_master industry_status_master { get; set; }
        public virtual industry_type_master industry_type_master { get; set; }
        public virtual river_basin_master river_basin_master { get; set; }
        public virtual river_subbasin_master river_subbasin_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<site_inspection_allocation> site_inspection_allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<site_inspection_conditions> site_inspection_conditions { get; set; }
        public virtual user_details user_details { get; set; }
        public virtual user_details user_details1 { get; set; }
        public virtual village_master village_master { get; set; }
        public virtual unit_master unit_master { get; set; }
        public virtual status_proposed_industry status_proposed_industry { get; set; }
        public virtual village_master village_master1 { get; set; }
        public virtual water_source_master water_source_master { get; set; }
        public virtual water_source_availability_master water_source_availability_master { get; set; }
    }
}
